export const TOAST_IDS = {
  SUCCESS_LOGIN: "success_login",
  SUCCESS_OTP_GENERATION: "success_otp_generation",
  OTP_VALID: "otp_valid",
  OTP_INVALID: "otp_invalid",
  SUCCESS_PASSWORD_UPDATE: "success_password_update",
  SUCCESS_REGISTER_USER: "success_register_user",
  SUCCESS_PRODUCT_CREATE: "success_product_create",
  SUCCESS_PRODUCT_CATEGORY_CREATE: "success_product_category_create",
  SUCCESS_PRODUCT_UNIT_CREATE: "success_product_unit_create",
  SUCCESS_PRODUCT_UPDATE: "success_product_update",
  SUCCESS_PRODUCT_DELETE: "success_product_delete",
  SUCCESS_CONTACT_CREATE: "success_contact_create",
  SUCCESS_CONTACT_UPDATE: "success_contact_update",
  SUCCESS_CONTACT_DELETE: "success_contact_delete",
  ERROR_CONTACT_CREATE: "error_contact_create",
  ERROR_CONTACT_UPDATE: "error_contact_update",
  ERROR_CONTACT_DELETE: "error_contact_delete",
  ERROR_PRODUCT_CREATE: "error_product_create",
  ERROR_PRODUCT_UPDATE: "error_product_update",
  ERROR_PRODUCT_DELETE: "error_product_delete",
};
